from playwright.sync_api import sync_playwright
import subprocess, time, json, urllib.request, os, sys

env = dict(os.environ)
env["SQUAD_DB_FILE"] = "/tmp/squad_btest.json"
env["SQUAD_BASE_URL"] = "http://127.0.0.1:3901/squadup"
env["PORT"] = "3901"
if os.path.exists("/tmp/squad_btest.json"): os.remove("/tmp/squad_btest.json")
srv = subprocess.Popen(["node","server/index.js"], cwd=os.path.dirname(os.path.abspath(__file__)), env=env,
                       stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
time.sleep(1.5)

def api(path, body):
    r = urllib.request.Request("http://127.0.0.1:3901"+path,
        data=json.dumps(body).encode(), headers={"Content-Type":"application/json"})
    return json.load(urllib.request.urlopen(r))

fails=[]
def check(c,m):
    print(("  ok: " if c else "  FAIL: ")+m)
    if not c: fails.append(m)

try:
    gin = api("/squadup/api/signup", {"name":"Gin","email":"g@t.test"})
    em  = api("/squadup/api/signup", {"name":"Emily","email":"e@t.test"})
    act = api("/squadup/api/activity", {"token":gin["token"],"title":"Climbing",
          "tag_name":"Climbing","primary":"2030-04-18T18:00","backup":"2030-04-17T18:00"})
    A = act["id"]

    with sync_playwright() as p:
        b = p.chromium.launch()
        errs=[]
        pg = b.new_page(viewport={"width":400,"height":800})
        pg.on("pageerror", lambda e: errs.append(str(e)))
        # font requests fail in an offline sandbox; any other failed load still counts
        pg.on("console", lambda m: errs.append("console."+m.type+": "+m.text)
              if m.type=="error" and "Failed to load resource" not in m.text else None)
        pg.on("requestfailed", lambda r: errs.append("request failed: "+r.url)
              if "fonts.g" not in r.url else None)

        print("=== clicking RSVP in a real browser ===")
        pg.goto(f"http://127.0.0.1:3901/squadup/a/{A}?t={em['token']}")
        pg.wait_for_load_state("networkidle")
        pg.locator("[data-vote]").first.click()
        pg.wait_for_load_state("networkidle"); pg.wait_for_timeout(600)
        body = pg.content()
        check("Emily" in body, "clicking a time records the RSVP and shows the name")
        check(not errs, "no JS errors on the activity page: "+str(errs[:2]))

        print("\n=== suggest another time via the UI ===")
        errs.clear()
        pg.locator("#suggest").click()
        pg.wait_for_timeout(200)
        check(pg.locator("#sugbox").is_visible(), "the suggest panel opens")
        pg.locator("#sugwhen").fill("2030-04-19T19:00")
        pg.locator("#sugnote").fill("after work")
        pg.locator("#sugsend").click()
        pg.wait_for_load_state("networkidle"); pg.wait_for_timeout(600)
        check(not errs, "no JS errors submitting a suggestion: "+str(errs[:2]))

        print("\n=== creator approves it ===")
        errs.clear()
        pg.goto(f"http://127.0.0.1:3901/squadup/a/{A}?t={gin['token']}")
        pg.wait_for_load_state("networkidle")
        check(pg.locator("[data-approve]").count()==1, "creator sees the approve control")
        pg.locator("[data-approve]").first.click()
        pg.wait_for_load_state("networkidle"); pg.wait_for_timeout(600)
        check("Apr 19" in pg.content(), "approving puts it on the board")
        check(not errs, "no JS errors approving: "+str(errs[:2]))

        print("\n=== a stranger joins from the activity link ===")
        errs.clear()
        pg2 = b.new_page(viewport={"width":400,"height":800})
        pg2.on("pageerror", lambda e: errs.append(str(e)))
        pg2.goto(f"http://127.0.0.1:3901/squadup/a/{A}")
        pg2.wait_for_load_state("networkidle")
        check(pg2.locator("#join").count()==1, "a signed-out visitor sees the join form")
        check(pg2.locator("[data-approve]").count()==0, "and cannot see pending suggestions")
        pg2.locator("#jname").fill("Lainee")
        pg2.locator("#jemail").fill("lainee@t.test")
        pg2.locator("#join").click()
        pg2.wait_for_load_state("networkidle"); pg2.wait_for_timeout(900)
        check("/squadup/a/" in pg2.url and "t=" in pg2.url, "they land back on the activity, signed in")
        check(not errs, "no JS errors during join: "+str(errs[:2]))

        print("\n=== opening a plan from the home page ===")
        errs.clear()
        pg.goto(f"http://127.0.0.1:3901/squadup/p/{em['token']}")
        pg.wait_for_load_state("networkidle")
        pg.locator("a.bubble", has_text="Climbing").first.click()
        pg.wait_for_load_state("networkidle")
        check(pg.locator("#join").count()==0 and pg.locator("[data-vote]").count()>0,
              "tapping a plan opens it signed in, ready to vote")

        print("\n=== subscriptions toggle on the personal page ===")
        errs.clear()
        pg.goto(f"http://127.0.0.1:3901/squadup/p/{gin['token']}")
        pg.wait_for_load_state("networkidle")
        chip = pg.locator(".chip").first
        chip.click(); pg.wait_for_timeout(700)
        check("on" not in (chip.get_attribute("class") or ""), "tapping a category turns it off")
        check(not errs, "no JS errors toggling: "+str(errs[:2]))

        print("\n=== new activity form ===")
        errs.clear()
        pg.goto(f"http://127.0.0.1:3901/squadup/new?t={gin['token']}")
        pg.wait_for_load_state("networkidle")
        pg.locator("#title").fill("Beach day")
        pg.select_option("#tag","__new")
        pg.wait_for_timeout(200)
        check(pg.locator("#newtag").is_visible(), "choosing a new category reveals the name field")
        pg.locator("#tagname").fill("Beach")
        pg.locator("#p1").fill("2030-05-01T11:00")
        pg.locator("#go").click()
        pg.wait_for_load_state("networkidle"); pg.wait_for_timeout(900)
        check("/squadup/a/" in pg.url, "posting lands on the new activity")
        check("Beach day" in pg.content(), "and it shows the title")
        check(not errs, "no JS errors posting: "+str(errs[:2]))

        print("\n=== let's do this sometime ===")
        errs.clear()
        pg.goto(f"http://127.0.0.1:3901/squadup/p/{em['token']}")
        pg.wait_for_load_state("networkidle")
        pg.locator("#ideaopen").click()
        check(pg.locator("#ideabox").is_visible(), "the add form opens")
        pg.locator("#ititle").fill("Kayaking the Caloosahatchee")
        pg.select_option("#tag", "__new")
        pg.locator("#tagname").fill("Water")
        pg.locator("#inote").fill("Rentals at the park")
        pg.locator("#ideago").click()
        pg.wait_for_load_state("networkidle"); pg.wait_for_timeout(900)
        card = pg.locator(".bubble.idea", has_text="Kayaking")
        check(card.count() == 1, "the new idea appears on the list")
        check(card.locator(".orb b").inner_text() == "1", "with the poster already in")
        check(not errs, "no JS errors adding an idea: "+str(errs[:2]))

        errs.clear()
        pg.goto(f"http://127.0.0.1:3901/squadup/p/{gin['token']}")
        pg.wait_for_load_state("networkidle")
        card = pg.locator(".bubble.idea", has_text="Kayaking")
        card.locator("[data-join]").click()
        pg.wait_for_load_state("networkidle"); pg.wait_for_timeout(900)
        card = pg.locator(".bubble.idea", has_text="Kayaking")
        check(card.locator(".orb b").inner_text() == "2" and "You're in" in card.inner_text(),
              "tapping I'm in adds your name")
        pg.once("dialog", lambda d: d.accept())
        card.locator("[data-nudge]").click()
        pg.wait_for_load_state("networkidle"); pg.wait_for_timeout(900)
        card = pg.locator(".bubble.idea", has_text="Kayaking")
        check("Next nudge" in card.inner_text(), "the nudge goes out and the button retires for the week")
        check(not errs, "no JS errors joining and nudging: "+str(errs[:2]))
        pg.set_viewport_size({"width":390,"height":844})
        pg.locator("#ideas").scroll_into_view_if_needed()
        pg.screenshot(path="/tmp/squadup_ideas_mobile.png", full_page=True)

        errs.clear()
        card.locator("a.pill", has_text="Pick a time").click()
        pg.wait_for_load_state("networkidle")
        check(pg.locator("#title").input_value() == "Kayaking the Caloosahatchee",
              "Pick a time opens the form pre-filled")
        pg.locator("#p1").fill("2030-06-06T09:00")
        pg.locator("#go").click()
        pg.wait_for_load_state("networkidle"); pg.wait_for_timeout(900)
        check("/squadup/a/" in pg.url, "posting it lands on the new activity")
        pg.goto(f"http://127.0.0.1:3901/squadup/p/{gin['token']}")
        pg.wait_for_load_state("networkidle")
        check(pg.locator(".bubble.idea", has_text="Kayaking").count() == 0,
              "and the idea is off the list")
        check(pg.locator("a.bubble", has_text="Kayaking").count() == 1,
              "replaced by the scheduled activity above it")
        check(not errs, "no JS errors scheduling an idea: "+str(errs[:2]))

        print("\n=== location, edit, one-tap, delete, past plans ===")
        H = "http://127.0.0.1:3901"
        SHOTS = "/tmp/claude-0/-home-claude/db9fdcab-d90c-5c91-90ad-49dfc5134cf7/scratchpad/"
        errs.clear()
        pg.goto(f"{H}/squadup/new?t={gin['token']}")
        pg.wait_for_load_state("networkidle")
        pg.locator("#title").fill("Pickleball")
        pg.locator("#loc").fill("Josh's place on the far side of the river by the old mill")
        pg.select_option("#tag", "__new"); pg.locator("#tagname").fill("Pickleball")
        pg.locator("#p1").fill("2030-06-06T18:00")
        check(pg.locator("#p2").is_visible() and pg.locator("#bkdel").is_visible(),
              "the backup box shows by default, with a Remove")
        pg.locator("#p2").focus()
        check(pg.locator("#p2").input_value() == "2030-06-06T18:00", "the backup starts from the main time")
        pg.locator("#p2").fill("2030-06-07T18:00")
        pg.locator("#go").click()
        pg.wait_for_url("**/squadup/a/**"); pg.wait_for_load_state("networkidle")
        PK = pg.url.split("/squadup/a/")[1].split("?")[0]
        check("at Josh" in pg.locator("h1").inner_text(), "the place shows in the plan's title")
        check(pg.locator("[data-vote].on").count() == 2, "the creator is already in for both times")
        check(not errs, "no JS errors posting with a place: "+str(errs[:2]))

        pg.goto(f"{H}/squadup/p/{em['token']}")
        pg.wait_for_load_state("networkidle")
        h3 = pg.locator(".row-card h3", has_text="Pickleball").first
        box = h3.bounding_box()
        check(box and box["height"] < 60, "a long title is cut to two lines on the card")
        check(pg.locator(".sub", has_text="No date yet").count() == 1, "the ideas section explains itself")
        pg.screenshot(path=SHOTS+"home.png", full_page=True)

        errs.clear()
        pg.goto(f"{H}/squadup/a/{PK}?t={gin['token']}")
        pg.locator("a.pill", has_text="Edit").click()
        pg.wait_for_url("**/squadup/edit/**"); pg.wait_for_load_state("networkidle")
        check(pg.locator("#loc").input_value().startswith("Josh"), "Edit opens the form filled in")
        pg.locator("#loc").fill("Josh's place")
        pg.locator("#p1").fill("2030-06-13T18:00")
        pg.locator("#go").click()
        pg.wait_for_url("**/squadup/a/**"); pg.wait_for_load_state("networkidle")
        check("Jun 13" in pg.content(), "saving lands back on the plan with the new time")
        check(not errs, "no JS errors editing: "+str(errs[:2]))

        errs.clear()
        pg.goto(f"{H}/squadup/r/{PK}?t={em['token']}&do=all")
        pg.wait_for_url("**saved=in**"); pg.wait_for_load_state("networkidle")
        check(pg.locator(".bubble.saved").count() == 1, "a one-tap email link saves and confirms")
        check(pg.locator("[data-vote].on").count() == 2, "both times are marked")
        check(not errs, "no JS errors on the one-tap page: "+str(errs[:2]))
        pg.screenshot(path=SHOTS+"plan.png", full_page=True)

        errs.clear()
        pg.goto(f"{H}/squadup/edit/{PK}?t={gin['token']}")
        pg.wait_for_load_state("networkidle")
        pg.once("dialog", lambda d: d.accept("Rain"))
        pg.locator("#del").click()
        pg.wait_for_url("**/squadup/a/**"); pg.wait_for_load_state("networkidle")
        check("deleted" in pg.content(), "Delete plan marks it deleted")
        pg.goto(f"{H}/squadup/p/{gin['token']}")
        pg.locator("a.pill", has_text="Past plans").click()
        pg.wait_for_url("**/squadup/past**"); pg.wait_for_load_state("networkidle")
        check(pg.locator(".bubble.past", has_text="Pickleball").count() == 1, "it shows up in Past plans")
        pg.screenshot(path=SHOTS+"past.png", full_page=True)
        pg.locator(".bubble.past", has_text="Pickleball").locator("a.pill", has_text="Do it again").click()
        pg.wait_for_url("**again=**"); pg.wait_for_load_state("networkidle")
        check(pg.locator("#title").input_value() == "Pickleball" and pg.locator("#p1").input_value() == "",
              "Do it again opens a fresh form with the details filled in")
        check(not errs, "no JS errors deleting or on past plans: "+str(errs[:2]))

        print("\n=== backup left blank, and getting home ===")
        errs.clear()
        def post_plan(title, add_then_remove):
            pg.goto(f"{H}/squadup/new?t={gin['token']}")
            pg.wait_for_load_state("networkidle")
            pg.locator("#title").fill(title)
            pg.select_option("#tag", "__new"); pg.locator("#tagname").fill("Climbing")
            pg.locator("#p1").fill("2030-09-01T09:00")
            if add_then_remove:
                pg.locator("#p2").fill("2030-09-02T09:00"); pg.locator("#bkdel").click()
                check(pg.locator("#bkadd").is_visible(), "after Remove, + Backup time brings it back")
            pg.locator("#go").click()
            pg.wait_for_url("**/squadup/a/**"); pg.wait_for_load_state("networkidle")
            return pg.locator(".bubble.opt").count()
        check(post_plan("No backup", False) == 1, "leaving the backup blank posts just one time")
        check(post_plan("Backup removed", True) == 1, "filling in a backup then removing it posts just one time")
        home_btn = pg.locator("header a.homebtn")
        check(home_btn.count() == 1 and "Home" in home_btn.inner_text(), "plan pages have a Home button up top")
        home_btn.click(); pg.wait_for_url("**/squadup/p/**"); pg.wait_for_load_state("networkidle")
        check(pg.locator("header a.homebtn").count() == 0, "it goes home, where it isn't needed")
        pg.goto(f"{H}/squadup/past?t={gin['token']}")
        check(pg.locator("header a.homebtn").count() == 1, "Past plans has it too")
        pg.goto(f"{H}/squadup/new?t={gin['token']}")
        pg.wait_for_load_state("networkidle")
        pg.screenshot(path=SHOTS+"newform.png")
        check(not errs, "no JS errors: "+str(errs[:2]))

        print("\n=== invites ===")
        errs.clear()
        CT = api("/squadup/api/activity", {"token":gin["token"],"title":"Catan","location":"Gin's",
              "tag_name":"Board games","primary":"2030-08-01T19:00","backup":"2030-08-02T19:00"})["id"]
        api("/squadup/api/signup", {"name":"Will","email":"w@t.test"})
        pg.goto(f"{H}/squadup/a/{CT}?t={gin['token']}")
        pg.wait_for_load_state("networkidle")
        pg.locator("#inviteopen").click()
        check(pg.locator("#invitebox").is_visible(), "Invite people opens the picker")
        check(pg.locator("#invitesend").is_disabled(), "the send button waits until you pick someone")
        pg.locator("[data-invitee]", has_text="Emily").click()
        pg.locator("[data-invitee]", has_text="Will").click()
        check(pg.locator("#invitesend").inner_text() == "Invite 2", "the button counts who you picked")
        pg.locator("#invitesend").click()
        pg.wait_for_url("**invited=**"); pg.wait_for_load_state("networkidle")
        check("Invited 2." in pg.content(), "it confirms")
        check(pg.locator(".person", has_text="Emily").count() == 1 and pg.locator(".person", has_text="Will").count() == 1,
              "both show under Invited")
        check(pg.locator("[data-invitee]", has_text="Emily").count() == 0, "and they drop out of the picker")
        check(not errs, "no JS errors inviting: "+str(errs[:2]))
        api("/squadup/api/reply", {"token":em["token"],"activity_id":CT,"do":"all"})
        pg.goto(f"{H}/squadup/a/{CT}?t={gin['token']}#invited")
        pg.wait_for_load_state("networkidle")
        pg.screenshot(path=SHOTS+"invite.png", full_page=True)

        b.close()
finally:
    srv.terminate()

print("\n"+("BROWSER FAILURES:\n - "+"\n - ".join(fails) if fails else "ALL BROWSER CHECKS PASSED"))
sys.exit(1 if fails else 0)
